### ISSUE TITLE
Warnings in serdes_1_to_5_diff_data

### ISSUE THREAD

**Issue by shenki** [timvideos/HDMI2USB-jahanzeb-firmware#88]
This looks like a real warning:

```
"hdl/hdmi/serdes_1_to_5_diff_data.v" Line 251: Result of 2-bit expression is truncated to fit in 1-bit target.
```

The code looks like this, with the warning referring to the last line of this snippet:

```
  wire       busy_data;
  wire [1:0] busy_data_or;

assign busy_data_or[0] = 1'b0 ;
assign busy_data_or[1] = busy_data | busy_data_or;       // The busy signals just need an OR gate
```

I would guess that the line should read as follows, but I haven't tested it:

```
assign busy_data_or[1] = busy_data | busy_data_or[1];
```

**Comment by shenki** [comment]
This issue blocks #38

**Comment by cfelton** [comment]
You don't want to have feedback in the assignment and it would produce different behavior than you currently have.  I don't think you want what you listed above.  

It should be or'd with the 'busy_data_or[0]' which is weird because 'busy_data_or[1]' will always equal 'busy_data'.  Looking at the rest of the code it looks like 'busy_data_or' should simply be removed and replaced with 'busy_data'.  

And the previous (not in the snippet but in the source) and-or assignments are an odd way to make a mux when you can generate a 1bit mux in a more readable fashion without loss of performance (i.e. gate delay).

**Comment by mithro** [comment]
This code is from Xilinx, so it would be a good idea to understand e
If this is something we have changed or if it was there original code.

**Comment by cfelton** [comment]
If there were changes it was before it was in the current git repo.  Any additional information where this came from?  Was it generated with coregen?  Is it a Xilinx example code?  Or simply mark these warnings as known and benign?

**Comment by mithro** [comment]
I believe it came from
http://www.xilinx.com/support/documentation/application_notes/xapp495_S6TMDS_Video_Interface.pdf

Which has some relationship to
http://www.xilinx.com/support/documentation/application_notes/xapp1064.pdf

Understanding the full origin of all the code is on my TODO list.

**Comment by shenki** [comment]
To save anyone else the trouble, the code @mithro linked to has the same issue as the version in our repository.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
